# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://dapmaster.cybr.com'
    conjuraccount: 'cyberark'
    conjurusername: 'host/pipeline-consumers/agent01'
    conjurapikey: '$(conjurkey1)'
    ignoreSsl: true
    secretsyml: secrets.yml
     

- script: echo $(SqlServerName) $(SqlToken)

